huggingface:
  api_key: xxxx
  embedding_model_name: thenlper/gte-large #"thenlper/gte-large", "BAAI/bge-large-en", "intfloat/e5-large-v2"
  batch_size: 16
  normalize_embeddings: true

data: # this is the settings for the data directory, directory is configurable
  directory:
    - ../data/csvs
    - ../data/pdfs

parse_pdf:
  chunk_size: 1000
  chunk_overlap: 50

validation_file:
  ../llm_gt.csv